{% set name = "graphtools" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/KrishnaswamyLab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: f93e653fe5db486a5b4abfa475fb588810d0e651beb87d52a0819c38b988290e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - future
    - numpy >=1.14.0
    - pygsp >=0.5.1
    - python
    - scikit-learn >=0.19.1
    - scipy >=1.1.0
    - tasklogger >=0.2

test:
  imports:
    - graphtools

about:
  home: https://github.com/KrishnaswamyLab/graphtools
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: graphtools, tools for building and manipulating graphs in Python.

extra:
  recipe-maintainers:
    - bebatut
