{% set name = "graphtools" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b35ae2974d24c507fe01b110d10b1d8c949e20bc49ff9d7d04f94849f9795907

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - future
    - numpy >=1.14.0
    - pygsp >=0.5.1
    - python >=3.5
    - scikit-learn >=0.20.0
    - scipy >=1.1.0
    - tasklogger >=1.0
    - deprecated

test:
  imports:
    - graphtools

about:
  home: https://github.com/KrishnaswamyLab/graphtools
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: graphtools, tools for building and manipulating graphs in Python.

extra:
  recipe-maintainers:
    - bebatut
    - scottgigante
